build: Remove unused pkg_deb
I cannot build all of tink-backend-aggregation because of this target,
which is very old and unused:

```
ERROR: /home/sebelino/src/tink-backend-aggregation/deb/BUILD:72:8: MakeDeb deb/tink-backend-aggregation__amd64.deb failed (Exit 1) make_deb failed: error executing command bazel-out/host/bin/external/rules_pkg/make_deb '--output=bazel-out/k8-fastbuild/bin/deb/tink-backend-aggregation__amd64.deb' ... (remaining 18 argument(s) skipped)
```

This target has been unused since the birth of tink-backend-aggregation
anyway, so let's remove it.