ci(docker-compose): COMPOSE_HTTP_TIMEOUT 60 -> 120
Attempt to mitigate these errors seen in the CI pipeline for the unit
test step:

```
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```